### ISSUE TITLE
Override `ForEach()` function for CUDA Matrix classes

### ISSUE THREAD

**Issue by mattldawson** [NCAR/micm#394]
Acceptance Criteria:
- `ForEach()` function for `CudaMatrix` and `CudaSparseMatrix` executes on device
- @sjsprecious - should there be performance criteria as well?

**Comment by sjsprecious** [comment]
According to the discussion with @mattldawson and @K20shores , instead of using the `foreach` function, we could also use some standard libraries like KPP does (https://github.com/KineticPreProcessor/KPP/blob/main/int/rosenbrock.c#L538-L570). There should be both CPU and GPU versions available.

Need to evaluate its impact on the performance in some ways.

**Comment by sjsprecious** [comment]
The CUDA version of `Foreach` is introduced into `CudaVectorMatrix` class through https://github.com/NCAR/micm/pull/422.

**Comment by sjsprecious** [comment]
I think we still need this issue open for the `CudaSparseMatrix` class unless it could inherit the same function from `CudaVectorMatrix` class. Am I wrong here? @mattldawson

**Comment by mattldawson** [comment]
> I think we still need this issue open for the `CudaSparseMatrix` class unless it could inherit the same function from `CudaVectorMatrix` class. Am I wrong here? @mattldawson

ah! sorry, I'll reopen it

**Comment by sjsprecious** [comment]
After discussing with @mattldawson , the `Foreach` function may not be used for the `SparseMatrix` or `CudaSparseMatrix` class. Close this issue for now.
