### ISSUE TITLE
Error message about NVCC and CXX flags

### ISSUE THREAD

**Issue by sjsprecious** [NCAR/micm#401]
When compiling the CUDA kernel in MICM, I got the following warning message:
```
nvcc warning : The -std=c++20 flag is not supported with the configured host compiler. Flag will be ignored.
```
This may be an issue from CMake side.

**Comment by mwaxmonsky** [comment]
Just ran a test build and it looks like this is only an issue when we compile `*.cu` files.  The rest of the library looks to build fine with `-std=c++20` and doesn't have the error.

My suspicion was that it was a combination of cmake not giving it the proper flag (https://docs.nvidia.com/cuda/cuda-compiler-driver-nvcc/index.html#std-c-03-c-11-c-14-c-17-c-20-std) and nvcc but apparently, even even compiling with `--std` flag instead of `-std` still produces the error:
```shell
> nvcc -forward-unknown-to-host-compiler -DDEFAULT_VECTOR_SIZE=4 -DUSE_JSON -O3 -DNDEBUG --std=c++20 --generate-code=arch=compute_70,code=[compute_70,sm_70] -MD -MT test.cu.o -MF test.cu.o.d -x cu -c test.cu -o test.cu.o
nvcc warning : The -std=c++20 flag is not supported with the configured host compiler. Flag will be ignored.
```

**Comment by sjsprecious** [comment]
This warning message is not observed in the GitHub Actions (e.g., https://github.com/NCAR/micm/actions/runs/9457328891/job/26050928184). Thus it seems to be a Derecho-specific issue (the nvhpc compiler is not built with the newer gcc version).
