### ISSUE TITLE
Some data in the State variable may be corrupt

### ISSUE THREAD

**Issue by sjsprecious** [NCAR/micm#625]
As identified by this issue https://github.com/NCAR/MUSICA-Performance-Comparison/issues/62, if we reuse the `State` variable between different iterations of `solve` function, the results are corrupt and we get `fail to converge` error message later.

Kyle commented that this was also the reason why he had to initialize the LU matrix to zero originally (https://github.com/NCAR/micm/issues/587).

This issue indicates that the LU matrix in `State` variable is not overwritten correctly between iterations (or we should not expect it to be overwritten correctly at all?).

**Comment by K20shores** [comment]
The `state` should be completely reusable. The fact that it isn't is a problem

**Comment by sjsprecious** [comment]
Thanks Kyle for the clarification. I looked at these two lines https://github.com/NCAR/micm/blob/main/include/micm/solver/lu_decomposition.inl#L201 and https://github.com/NCAR/micm/blob/main/include/micm/solver/lu_decomposition.inl#L214. Could the `Uvector` use the values from the previous time step without a zeroing?

**Comment by K20shores** [comment]
We set them just before those, but it's in an if block so maybe not all of the values are zeros. Perhaps we should add back a zero of L and U

**Comment by sjsprecious** [comment]
Thanks @K20shores for your comments. Hmm, interesting. For the first time when the `State` variable is generated, are the L and U matrices zeroed?

**Comment by K20shores** [comment]
I've learned some things. Thanks to @mattldawson's suggestion, I set the L and U matrices to Inf and found out that sometimes we end up with infs after the LU decomposition.

The issue seems to be related to the interplay between block size (which are grid cells) and the number of species. 

Sizes leading to valid L and U matrices

| Species (size) | Blocks (grid cells) |
|----------------|---------------------|
| 1              | 1                   |
| 2              | 1                   |
| 2              | 2                   |
| 3              | 2                   |

Sizes leading to L and U matrices with infs

| Species (size) | Blocks (grid cells) |
|----------------|---------------------|
| 3              | 1                   |
| 3              | 2                   |
| 3              | 3                   |
| 3              | 4                   |

**Comment by K20shores** [comment]
Also, the math on [geeks for geeks for the doolittle algorithm that we use](https://www.geeksforgeeks.org/doolittle-algorithm-lu-decomposition/) indicates that U should always take a value from the input matrix, but I can see in the debugger that on some cases it doesn't. I think this means we are missing some `do_aik_` values which are made in the initialize function

![Image](https://github.com/user-attachments/assets/bdf40e93-e6a9-4392-8a0e-7c2b6a366098)


https://github.com/NCAR/micm/blob/94c22da20e387f55dc0ccdb5c582668894b60e07/include/micm/solver/lu_decomposition.inl#L56-L66

**Comment by sjsprecious** [comment]
Thanks to @K20shores , we track down the issue further. Given an initial Jacobian matrix with size `4x4` and nonzero elements marked as `X` below:
```
X 0 0 0 
0 X X X 
X X X X 
0 X 0 X 
```
The expected L matrix should be:
```
X 0 0 0 
0 X 0 0 
X X X 0 
0 X X X 
```
While we are constructing the third element of the fourth row,`L[3][2]` is not overwritten by the corresponding Jacobian matrix element first. https://github.com/NCAR/micm/blob/94c22da20e387f55dc0ccdb5c582668894b60e07/include/micm/solver/lu_decomposition.inl#L211
Since we are initializing the `L` matrix with `inf` now, this leads to a `inf - some value` operation later and corrupts the result.
https://github.com/NCAR/micm/blob/94c22da20e387f55dc0ccdb5c582668894b60e07/include/micm/solver/lu_decomposition.inl#L214

After discussion with Kyle, the lines https://github.com/NCAR/micm/blob/94c22da20e387f55dc0ccdb5c582668894b60e07/include/micm/solver/lu_decomposition.inl#L56 and https://github.com/NCAR/micm/blob/94c22da20e387f55dc0ccdb5c582668894b60e07/include/micm/solver/lu_decomposition.inl#L85 can be problematic. The nonzero index of lower and upper matrices should be set by checking the lower and upper matrices themselves, rather than the Jacobian matrix unless we have a misunderstanding of what is going on here.

**Comment by K20shores** [comment]
@jian helped me pin down the problem.

The issue is that the sparsity pattern of the LU matrices doesn't necessarily match the sparsity pattern of the jacobian matrix. In the algorithm, the LU matrices need to be filled with the value from the A matrix when the LU matrices are nonzero.

The first change we needed to make was to accurately record when to set the LU matrix values based off of when the LU matrices are zero, not the jacobian as was happening before.

The second change is to record a sentinel value. This value indicates when the L or U matrix is nonzero and the jacobian is actually zero. In this case, we set the LU matrix to zero rather than copying from the jacobian matrix.
