### ISSUE TITLE
Automate documentation builds

### ISSUE THREAD

**Issue by mattldawson** [NCAR/micm#96]
Automate documentation deployment to github.io using GH Actions. (Can follow the approach used for [TUV-x](https://github.com/NCAR/tuv-x)) and include a link in the README

**Comment by aharonYK** [comment]
Please assign me this issue I would like to contribute.

**Comment by mattldawson** [comment]
> Please assign me this issue I would like to contribute.

Hi Aharon, sure thing! Thanks!

**Comment by aharonYK** [comment]
do you want an entire site for documentation like TUV-x ?

**Comment by mattldawson** [comment]
Yeah, that's what we were thinking - there's not much documentation yet, but we will be adding more in the near future with tutorials, etc.

There is a GH action that builds the Sphinx documentation for TUV-x and puts it on the `gh-pages` branch if it's helpful: https://github.com/NCAR/tuv-x/blob/main/.github/workflows/gh-pages.yml

**Comment by K20shores** [comment]
You should be able to see the docs we do make. `cmake -DBUILD_DOCS=ON ..`, `make docs` should create the documentation in the build folder. You can open it up to see what the files look like locally. Because there's a cmake option, building the docs may be slightly simpler than what's needed for TUVx.

**Comment by aharonYK** [comment]
ok im on it
